import { Product } from '@/types/product';

export const products: Product[] = [
	{
		id: '1',
		slug: 'bpc-157',
		name: 'BPC 157',
		description: 'Tissue repair and recovery support for tendons, joints, and muscle health.',
		details: 'Often selected for soft-tissue support and post-training recovery routines, with a focus on mobility, comfort, and day-to-day resilience.',
		icons: ['Recovery', 'Longevity', 'Digestive'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v01.webp',
		category: 'Recovery',
		status: 'published',
	},
	{
		id: '2',
		slug: 'ghk-cu',
		name: 'GHK Cu',
		description: 'Skin rejuvenation peptide to support collagen, elasticity, and glow.',
		details: 'A copper peptide favored in dermal care protocols for tone and texture, supporting a smoother, brighter, and more refined appearance.',
		icons: ['Recovery', 'Skin'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v02.webp',
		category: 'Skin',
		status: 'published',
	},
	{
		id: '3',
		slug: 'glutathione',
		name: 'Glutathione',
		description: 'Master antioxidant support for detox pathways and cellular defense.',
		details: 'Used to support oxidative balance and cellular resilience, helping the body maintain clarity, recovery, and overall detox support.',
		icons: ['Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v03.webp',
		category: 'Antioxidant',
		status: 'published',
	},
	{
		id: '4',
		slug: 'ipamorelin',
		name: 'Ipamorelin',
		description: 'Gentle growth‑hormone support for recovery, sleep, and lean mass.',
		details: 'Commonly paired with nighttime recovery and restorative routines to support deeper rest, lean mass maintenance, and recovery cycles.',
		icons: ['Growth', 'Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v04.webp',
		category: 'Growth',
		status: 'published',
	},
	{
		id: '5',
		slug: 'mots-c',
		name: 'MOTS-C',
		description: 'Metabolic optimizer to support energy production and insulin balance.',
		details: 'Selected for metabolic efficiency and endurance support protocols, with an emphasis on steady energy output and glucose balance.',
		icons: ['Metabolic', 'Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v05.webp',
		category: 'Metabolic',
		status: 'published',
	},
	{
		id: '6',
		slug: 'retratrutide',
		name: 'Retatrutide',
		description: 'Triple‑agonist metabolic support for weight and glucose balance.',
		details: 'Advanced metabolic signaling support for body composition programs, helping to guide appetite, energy use, and glucose management.',
		icons: ['Metabolic'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v06.webp',
		category: 'Metabolic',
		status: 'published',
	},
	{
		id: '7',
		slug: 'tb-500',
		name: 'TB 500',
		description: 'Systemic recovery peptide to support mobility and soft‑tissue repair.',
		details: 'Often used in mobility-focused recovery stacks to support soft-tissue repair, flexibility, and smoother movement over time.',
		icons: ['Recovery'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v07.webp',
		category: 'Recovery',
		status: 'published',
	},
	{
		id: '8',
		slug: 'tirzepatide',
		name: 'Tirzepatide',
		description: 'Dual‑agonist support for metabolic health and body composition.',
		details: 'Supports appetite signaling and metabolic balance goals, often selected for structured wellness and body composition routines.',
		icons: ['Balance', 'Performance', 'Natural'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v08.webp',
		category: 'Metabolic',
		status: 'published',
	},
	{
		id: '9',
		slug: 'tesamorelin',
		name: 'Tesamorelin',
		description: 'Longevity‑focused peptide to support fat metabolism and recovery.',
		details: 'Used in longevity routines for metabolic and recovery support, with an emphasis on healthy aging and ongoing vitality.',
		icons: ['Growth', 'Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v09.webp',
		category: 'Longevity',
		status: 'published',
	},
	{
		id: '10',
		slug: 'selank',
		name: 'Selank',
		description: 'A synthetic nootropic peptide derived from tuftsin, studied for its potential effects on cognitive function and stress response.',
		details: 'Selank is a heptapeptide researched for its anxiolytic and nootropic properties. Studies have explored its interaction with GABA receptors and its potential role in modulating neurotransmitter levels. Commonly investigated in cognitive and behavioral research models.',
		icons: ['Cognitive'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v01.webp',
		category: 'Cognitive',
		status: 'published',
	},
	{
		id: '11',
		slug: 'semax',
		name: 'Semax',
		description: 'A synthetic peptide analog of ACTH, researched for its neuroprotective and cognitive-enhancing properties.',
		details: 'Semax is a heptapeptide studied for its effects on brain-derived neurotrophic factor (BDNF) and its potential neuroprotective mechanisms. Research has explored its role in cognitive function, memory, and neuronal health in various laboratory models.',
		icons: ['Cognitive'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v02.webp',
		category: 'Cognitive',
		status: 'published',
	},
	{
		id: '12',
		slug: 'cjc-without-dac',
		name: 'CJC without DAC',
		description: 'A growth hormone releasing hormone analog researched for its effects on growth hormone secretion.',
		details: 'CJC-1295 without Drug Affinity Complex (DAC) is a modified GHRH peptide with a shorter half-life. It has been studied for its pulsatile stimulation of growth hormone release, making it a subject of interest in metabolic and growth-related research.',
		icons: ['Growth'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v03.webp',
		category: 'Growth',
		status: 'published',
	},
	{
		id: '13',
		slug: 'kpv',
		name: 'KPV',
		description: 'A naturally occurring tripeptide derived from alpha-MSH, studied for its anti-inflammatory properties.',
		details: 'KPV (Lys-Pro-Val) is the C-terminal tripeptide of α-MSH. Research has focused on its potent anti-inflammatory effects and its potential role in modulating immune responses. Studies have explored its mechanisms in various inflammatory research models.',
		icons: ['Recovery', 'Digestive'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v04.webp',
		category: 'Immune',
		status: 'published',
	},
	{
		id: '14',
		slug: 'pt-141',
		name: 'PT-141',
		description: 'A synthetic melanocortin receptor agonist researched for its effects on melanocortin pathways and sexual function.',
		details: 'PT-141 is a cyclic heptapeptide that acts on melanocortin receptors MC3R and MC4R. Research has explored its unique mechanism of action through the central nervous system, making it a subject of interest in behavioral and physiological studies.',
		icons: ['Intimacy'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v05.webp',
		category: 'Sexual Health',
		status: 'published',
	},
	{
		id: '15',
		slug: 'ara-290',
		name: 'ARA-290',
		description: 'A non-erythropoietic peptide derived from EPO, researched for tissue-protective and regenerative properties.',
		details: 'ARA-290 is an 11 amino acid peptide that selectively activates the innate repair receptor without stimulating red blood cell production. Research has explored its potential in neuroprotection, tissue repair, and metabolic regulation.',
		icons: ['Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v06.webp',
		category: 'Recovery',
		status: 'published',
	},
	{
		id: '16',
		slug: 'bacteriostatic-water',
		name: 'Bacteriostatic Water',
		description: 'Sterile water containing 0.9% benzyl alcohol as a bacteriostatic preservative for reconstituting lyophilized compounds.',
		details: 'Bacteriostatic water is an essential laboratory supply for reconstituting peptides and other lyophilized research compounds. The benzyl alcohol preservative inhibits bacterial growth, allowing for multiple uses from a single vial.',
		icons: ['Hydration'],
		price: 10.99,
		stock: 50,
		image: '/bottles/v07.webp',
		category: 'Supplies',
		status: 'published',
	},
	{
		id: '17',
		slug: 'epitalon',
		name: 'Epitalon',
		description: 'A synthetic tetrapeptide studied for its potential effects on telomerase activity and cellular aging mechanisms.',
		details: 'Epitalon (Ala-Glu-Asp-Gly) is based on the naturally occurring epithalamin peptide. Research has focused on its potential role in activating telomerase, the enzyme responsible for maintaining telomere length. Studies have explored its effects on cellular longevity.',
		icons: ['Longevity'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v08.webp',
		category: 'Longevity',
		status: 'published',
	},
	{
		id: '18',
		slug: 'vip',
		name: 'VIP',
		description: 'A 28-amino acid neuropeptide researched for its roles in immune regulation, neuroprotection, and vasodilation.',
		details: 'VIP (Vasoactive Intestinal Peptide) is a widely distributed peptide found in the central and peripheral nervous systems. Research has explored its diverse biological functions including anti-inflammatory effects, circadian rhythm regulation, and neuroprotective properties.',
		icons: ['Digestive'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v09.webp',
		category: 'Immune',
		status: 'published',
	},
	{
		id: '19',
		slug: 'wolverine-stack',
		name: 'Wolverine Stack',
		subtitle: 'BPC-157 10mg + TB-500 10mg',
		description: 'A powerful research combination of BPC-157 and TB-500, studied for their synergistic effects on tissue repair and recovery.',
		details: 'This research stack combines two peptides known for their regenerative properties. BPC-157 (Body Protection Compound) and TB-500 (Thymosin Beta-4 fragment) have been individually studied for their effects on soft tissue repair, mobility, and recovery mechanisms. Research suggests potential synergistic benefits when combined.',
		icons: ['Recovery', 'Muscle Health', 'Vitality'],
		price: 95.99,
		stock: 20,
		image: '/bottles/v10.webp',
		category: 'Stacks',
		status: 'published',
	},
	{
		id: '20',
		slug: 'glow-stack',
		name: 'Glow Stack',
		subtitle: 'BPC-157 10mg + TB-500 10mg + GHK-Cu 50mg',
		description: 'A skin and recovery focused research combination featuring tissue repair peptides enhanced with copper peptide for skin rejuvenation.',
		details: 'This stack builds on the Wolverine formula with the addition of GHK-Cu, a copper peptide researched for skin health and collagen synthesis. The combination has been studied for its potential effects on both internal tissue repair and external skin appearance, tone, and texture.',
		icons: ['Energy', 'Wellness', 'Recovery'],
		price: 125.99,
		stock: 20,
		image: '/bottles/v01.webp',
		category: 'Stacks',
		status: 'published',
	},
	{
		id: '21',
		slug: 'klow-stack',
		name: 'KLOW Stack',
		subtitle: 'BPC-157 10mg + TB-500 10mg + KPV 10mg + GHK-Cu 50mg',
		description: 'The most comprehensive research stack combining tissue repair, skin health, and anti-inflammatory peptides for full-spectrum support.',
		details: 'This advanced stack includes the Glow formula plus KPV, a tripeptide researched for its potent anti-inflammatory properties. The combination has been studied for synergistic effects on tissue repair, skin rejuvenation, and immune modulation, making it ideal for comprehensive wellness research protocols.',
		icons: ['Balance', 'Wellness', 'Recovery'],
		price: 155.99,
		stock: 20,
		image: '/bottles/v02.webp',
		category: 'Stacks',
		status: 'published',
	},
];
