import {
	Activity,
	Bone,
	Brain,
	Clock,
	Droplets,
	Flame,
	Flower2,
	Gauge,
	Heart,
	HeartPulse,
	Leaf,
	Moon,
	Pill,
	Scale,
	Shield,
	Sparkles,
	Sun,
	Timer,
	TrendingUp,
	Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
	Activity,
	Hydration: Droplets,
	Wellness: Flower2,
	Performance: Gauge,
	Vitality: HeartPulse,
	Natural: Leaf,
	Sleep: Moon,
	Balance: Scale,
	Energy: Sparkles,
	FastActing: Timer,
	Recovery: Zap,
	'Muscle Health': Bone,
	AntiAging: Clock,
	Cognitive: Brain,
	Immune: Shield,
	'Sexual Health': Heart,
	Metabolic: Flame,
	Growth: TrendingUp,
	Longevity: Clock,
	Skin: Sun,
	Digestive: Pill,
	Intimacy: Heart,
};
